### ISSUE TITLE
Transmit various commands from Frontend via Sensor to XCSOAR 

### ISSUE THREAD

**Issue by degeflija** [larus-breeze/sw_sensor#19]
über XCI oder über geeignetes Protokoll

**Comment by Simsys** [comment]
There now exists a NMEA Spezification: 
https://github.com/larus-breeze/doc_larus/blob/master/documentation/Larus_NMEA_Protocol.md

which is already implemented in XCSoar
https://github.com/XCSoar/XCSoar/pull/1423

**Comment by MaxBaex** [comment]
- Implement  **void format_PLARS ( float value, ENUM type, char * &p)**  for Balast, Bugs, MC and  QNH here:  https://github.com/larus-breeze/sw_algorithms_lib/blob/main/Output_Formatter/NMEA_format.cpp
- Implement **parser for $PLARS string** from XCSOAR for inserting it back onto the CAN as https://github.com/larus-breeze/doc_larus/blob/master/documentation/can_details/object_directory/vario_display.md#id-0x682-set-system-wide-config-item
- https://github.com/larus-breeze/doc_larus/blob/master/documentation/can_details/object_directory/sensorbox.md#id-0x522-set-system-wide-config-item

**Comment by MaxBaex** [comment]
Receiving commands back from XCSOAR requires the ESP32 firmware https://github.com/larus-breeze/sw_sensor/blob/master/sw_esp32/ESP32_sketch_BT_WLAN/ESP32_sketch_BT_WLAN.ino  to forward received frames back to the stm32 controller  via both:
- Bluetooth connection
- Serial connections

**Comment by MaxBaex** [comment]
Add the functionality to send the PLARS strings to corresponding received CAN Frames in the NMEA task.

**Comment by MaxBaex** [comment]
Waiting for Merge https://github.com/larus-breeze/sw_algorithms_lib/pull/34  before a pull request is created here.

**Comment by MaxBaex** [comment]
Further commands like 
    force to glide / force to climb
    force to north-up, force to course-up, force to wind-up
    switch on wave aid, switch off wave aid

are to be defined and discussed here first: https://github.com/larus-breeze/doc_larus/issues/8 
A new implementation issue shall be opened after the definition.
