### ISSUE TITLE
Add ADS-L capability

### ISSUE THREAD

**Issue by realtimepeople** [larus-breeze/sw_sensor#60]
EASA has published the protocol for ADS-L on 868 Mhz in this document:
https://www.easa.europa.eu/en/downloads/137503/en

We can easily add the capability to receive and even transmit ADS-L packets
using a SRD chipset wired to our SPI port.

This means that Larus can also provide air-safety information including
sending and receiving data compatible to FLARM.

**Comment by Simsys** [comment]
I think you need completely new hardware that can transmit and receive on the Flarm frequencies. It would be good if this hardware had two HF front ends (antenna diversity).

It is not much effort to then also provide a controller or to use a controller with an RF front end (e.g. incl. antenna diversity https://www.silabs.com/documents/public/data-sheets/efr32fg28-datasheet.pdf).

From my point of view, that doesn't fit here.

**Comment by Simsys** [comment]
After discussion: will not be realized in this project
