### ISSUE TITLE
CAN packet <c_CID_KSB_GPS_Sats> content inaccurate

### ISSUE THREAD

**Issue by degeflija** [larus-breeze/sw_sensor#63]
CAN paket reports "1" (== GPS_OK), when at the same time GPS status is better (GPS_2D or GPS_3D ...)

**Comment by MaxBaex** [comment]
c_CAN_Id_GPS_Sats Reports a valid Fix status in the first bit and the information if a DGNSS heading is available in the in the second bit.  2D  or 3D Fix could be reported in the third but but why is it needed or what is the use case?

**Comment by Simsys** [comment]
After discussion: we thing, the current solution is sufficient.
