### ISSUE TITLE
enhance sensor.readings output

### ISSUE THREAD

**Issue by MaxBaex** [larus-breeze/sw_sensor#73]
in https://github.com/larus-breeze/sw_sensor/blob/master/sw_stm32/Communication/sensor_dump.cpp
to improve debug ability. The output shall depending on the GNSS (Single GNSS, Differential GNSS) configuration in sensor_config.txt always output the following:

- DGNSS or Single GNSS configuration
- Fix valid and number of used satellites

Additionally for the DGNSS configuration:
- DGNSS-Hdg=:  [not available, or actual value]
- BaseLength= [not available, or actual value]
- SlaveDown= [not available, or actual value]

Currently the output only displays the DGNSS parameter if there is a valid heading fix. The output shall give the feedback if the DGNSS is basically correctly configured.

**Comment by realtimepeople** [comment]
Has been fixed with commit ID ea874afb15fc8e22f31c8be32e42ec045b012d2d
