### ISSUE TITLE
crashes caused by compromised sensor_config.txt values

### ISSUE THREAD

**Issue by Ventusfahrer** [larus-breeze/sw_sensor#88]
The Frontend was working fine when using the old sensor firmware (whatever version Stefan Langer initially installed on the box). 

In order to get the latest release on the sensor I flashed the 0.3.0 and put the new sensor_config.txt into Larus (essential version). 
After the first boot attempt the sensor box does not come up again.

The sensor box does only come up fine, when no SD Card was placed in the sensor box. Whenever an SD card was placed in the box, it crashes. Crash dumps were written to the SD-Card, so the car did have the right file system.

Modifized sensor_config.txt used by the first startup is attached.

[sensor_config.txt](https://github.com/larus-breeze/sw_sensor/files/14637722/sensor_config.txt)

**Comment by realtimepeople** [comment]
Fixed in release 3.1
