### ISSUE TITLE
NMEA transmission interval 

### ISSUE THREAD

**Issue by MaxBaex** [larus-breeze/sw_sensor#98]
is currently set to 250ms in sw_stm32/Core/Inc/system_configuration.h    #define NMEA_REPORTING_PERIOD	250 // period in clock ticks for NMEA output

Some pilots prefer a higher reporting period. Can the interval be changed to 100ms ?    The old Sensor Hardware Version 1.0. uses instead of the esp32 a very simple Bluetooth module. It needs to be verified if this module supports the higher datarate.

**Comment by realtimepeople** [comment]
According to August this is tha highest possible speed compatible with XCsoar.

**Comment by MaxBaex** [comment]
Closed as interval shortening does not seem useful.
